version: "3"
services:
  postgres:
    image: postgres
    command: postgres -p 5432 -c 'log_statement=all'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: 
      - dbdata:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d/

volumes:
  dbdata:
