# fly.toml app configuration file generated for unit-conversion-falling-bird-694 on 2025-09-28T10:29:23-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'unit-conversion-backend'
primary_region = 'sjc'

[build]
  dockerfile = 'backend/Dockerfile'
  [build.args]
    GO_VERSION = '1.21'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
